# Colours (Monokai Charcoal)

# Default Colours
[colors.primary]
background = '#060606'
foreground = '#FFFFFF'

[font]
normal = {family = "SFMonoNerdFontMono", style = "Regular"}
size = 12

# Normal Colours
[colors.normal]
black   = '#1a1a1a'
red     = '#f4005f'
green   = '#98e024'
yellow  = '#fa8419'
blue    = '#9d65ff'
magenta = '#f4005f'
cyan    = '#58d1eb'
white   = '#c4c5b5'

# Bright Colours
[colors.bright]
black   = '#625e4c'
red     = '#f4005f'
green   = '#98e024'
yellow  = '#e0d561'
blue    = '#9d65ff'
magenta = '#f4005f'
cyan    = '#58d1eb'
white   = '#f6f6ef'

[window]
opacity = 0.7

[window.padding]
x = 10
y = 10
